### ISSUE TITLE
Cannot specify datacenter different from global config

### ISSUE THREAD

**Issue by giner** [cloudfoundry/bosh-vsphere-cpi-release#136]
I'm trying to use multi-cpi with the latest version of vsphere-cpi (v50) and cannot make it work.

Conditions:
- two vcenters / two datacenters
- one vcenter + datacenter is specified in global configuration and another one is specified in cpi config
- multiple clusters per vcenter

Request:
```
D, [2018-08-17T08:53:16 #4086] [create_missing_vm(riemann/d962c405-a030-4196-a3bf-50e016cfc5ec (4)/1)] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-475203] request: {"method":"create_vm","arguments":["9ba0c5f3-5bdb-471b-8b09-063ec9ee9a8c","sc-49359b24-fe83-4d3d-85a4-560391f334ee",{"datacenters":"<redacted>","cpu":"<redacted>","disk":"<redacted>","ram":"<redacted>"},{"cf-mgmt-vsphere-component-azs":{"type":"manual","ip":"100.73.4.90","netmask":"255.255.255.0","cloud_properties":{"name":"<redacted>"},"default":["dns","gateway"],"dns":["100.64.0.1","100.64.0.33"],"gateway":"100.73.4.254"}},[],{"bosh":{"password":"<redacted>","mbus":"<redacted>","group":"bosh-lab-jpe2-vsphere-cf-lab-persistent-riemann","groups":["bosh-lab-jpe2-vsphere","cf-lab-persistent","riemann","bosh-lab-jpe2-vsphere-cf-lab-persistent","cf-lab-persistent-riemann","bosh-lab-jpe2-vsphere-cf-lab-persistent-riemann"]}}],"context":{"director_uuid":"5eca588d-4a94-4d6e-87de-e56fcccd936d","request_id":"cpi-475203","vcenter":"<redacted>"}} with command: /var/vcap/jobs/vsphere_cpi/bin/cpi
```
Response:
```
D, [2018-08-17T08:53:24 #4086] [create_missing_vm(riemann/d962c405-a030-4196-a3bf-50e016cfc5ec (4)/1)] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-475203] response: {"result":null,"error":{"type":"Unknown","message":"Can't find cluster 'JPE2-std-204'","ok_to_retry":false},"log":"Rescued Unknown: Can't find cluster 'JPE2-std-204'. backtrace: /var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/resources/cluster_provider.rb:13:in `find'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/vm_config.rb:144:in `block in find_clusters'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/vm_config.rb:142:in `each'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/vm_config.rb:142:in `find_clusters'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/vm_config.rb:20:in `cluster'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/vm_config.rb:117:in `validate_drs_rules'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/vm_config.rb:94:in `validate'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/cloud.rb:278:in `block in create_vm'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/cloud.rb:243:in `create_vm'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'\n/var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'\n/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:42:in `<top (required)>'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'\n/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'\n/var/vcap/data/packages/ruby-2.4-r4/45171c87752df306fb86c932ce09b24c665e97ca/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'\n/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'"}, err: /var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
```
CPI:
```
D, [2018-08-17T08:53:24.825733 #5199] DEBUG -- [req_id cpi-475203]: All clusters provided: {"JPE2-dev-01"=>#<VSphereCloud::ClusterConfig:0x000055f9a4530f90 @name="JPE2-dev-01", @config={}>}
D, [2018-08-17T08:53:24.825871 #5199] DEBUG -- [req_id cpi-475203]: Running method 'FindByInventoryPath'...
I, [2018-08-17T08:53:24.906191 #5199]  INFO -- [req_id cpi-475203]: Using global ephemeral disk datastore pattern: dev-nmbl..._dev01_.._pas
E, [2018-08-17T08:53:24.906464 #5199] ERROR -- [req_id cpi-475203]: Error in creating vm: Can't find cluster 'JPE2-std-204', Backtrace - /var/vcap/data/packages/vsphere_cpi/fb9cb832afdfde85a6c779b99825d51dca5ed98b/lib/cloud/vsphere/resources/cluster_provider.rb:13:in `find'
```
CPI config
```
cpis:
- name: vsphere-jpe2-pod2
  type: vsphere
  properties:
    vcenter:
      address: <different from global>
      ...
      datacenters:
      - name: <different from global>
        clusters:
        - JPE2-std-204
        - JPE2-std-205
        - JPE2-std-206
      ...
```

So it is trying to find cluster JPE2-std-204 (which is in datacenter specified by cpi config) but can only JPE2-dev-01 (which is specified in global config).

**Comment by nehagjain15** [comment]
@giner did your same config work for previous versions? Do you have your az's set to reference different cpi's?

**Comment by giner** [comment]
@nehagjain15 So far we've been using multiple clusters within single vcenter / datacenter.

It's the first time I'm trying to use multi-cpi. [Documentation](https://bosh.io/docs/cpi-config/#example) suggests it should work.

**Comment by giner** [comment]
Hi @nehagjain15, it is probably my fault. I assumed (which felt kind of obvious) that multi-cpi configuration was identical to cpi configuration in the [spec file](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/35b7a3ac9a65de3e88a6b1e0fbdb09df61b8171a/jobs/vsphere_cpi/spec) however it appeared to be different and it looks more like [this](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/35b7a3ac9a65de3e88a6b1e0fbdb09df61b8171a/jobs/vsphere_cpi/templates/cpi.json.erb#L9-L16). I'll check if this works and be back with the results.

**Comment by giner** [comment]
@nehagjain15, it works with the updated configuration. Still it seems to be confusing.

**Comment by nehagjain15** [comment]
I am glad that it worked. We will see if we can update the multi-cpi documentation to be more clear oaboutconfiguration

**Comment by dpb587-pivotal** [comment]
@giner regarding doc improvements, would you expect a different sort of vsphere example than the current one, or an additional note/comment somewhere on https://bosh.io/docs/cpi-config/#cpis?

**Comment by giner** [comment]
The example looks fine however it doesn't say where it comes from. The documentation says "These are the Global Configuration of a given CPI", that's why I copied global configuration to the cpi config however naming and structure in the global config is slightly different.

**Comment by giner** [comment]
I'm sorry, I was not clear on what is confusing.

Configuration in deployment:
```
properties:
  vcenter:
    address: 172.16.68.3
    user: root
    password: vmware
    datacenters:
      ...
```

Configuration in cpi-config:
```
properties:
  host: 172.16.68.3
  user: root
  password: vmware
  datacenters:
    ...
```

There are at least two differences above:
1) there is no vcenter in cpi-config
2) address vs host

Another thing is that my understanding was that "Global configuration" is the one you put in the deployment however checking here https://bosh.io/docs/vsphere-cpi/#global it looks like it is not the case because it is saying "host" and not "address".

**Comment by nehagjain15** [comment]
@giner This has been fixed. You can now specify host in deployment configuration as well.
