### ISSUE TITLE
detach_disks fails with 'Insufficient disk space on datastore'

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry/bosh-vsphere-cpi-release#150]
**Describe the bug**
During `detach_disks` the CPI checks if a persistent disk has the correct name, if not it tries to rename the disk to the expected name (disk-guid). Unfortunately it does so by simply extracting the `current_datastore` name, and wants to "rename" it without checking if said datastore still has enough free disk capacity.
A disk rename/move temporarily creates a copy on the datastore, and if there's not enough free space for that copy it will fail and leave BOSH / the disk in an error state.
https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/v50/src/vsphere_cpi/lib/cloud/vsphere/resources/vm.rb#L299-L309

**To Reproduce**
1. Create VMs with big persistent disks until a datastore would not have enough capacity anymore for another one.
2. Rename the persistent disk file of VM XYZ on VMware to something else.
3. Issue a BOSH command that would run `detach_disks` CPI method for VM XYZ.
4. Observe failure to rename/move disk.

**CPI Error Log**
```
I, [2018-09-14T17:25:22.336780 #1020]  INFO -- [req_id cpi-101361]: Found 1 persistent disk(s)
I, [2018-09-14T17:25:22.338424 #1020]  INFO -- [req_id cpi-101361]: Detaching: [wl01_ucs1_t2_wld_AC-ZHH-Prd-06_3007] vm-12e04237-3d13-4c3d-91ce-90939b3198aa/vm-12e04237-3d13-4c3d-91ce-90939b3198aa_7550.vmdk
D, [2018-09-14T17:25:22.470278 #1020] DEBUG -- [req_id cpi-101361]: Current file path is vm-12e04237-3d13-4c3d-91ce-90939b3198aa/vm-12e04237-3d13-4c3d-91ce-90939b3198aa_7550
D, [2018-09-14T17:25:22.470414 #1020] DEBUG -- [req_id cpi-101361]: Original file path is PSC_SCS/disks/disk-472ad9a9-2e29-4d30-a16c-2fbf75c341c1
D, [2018-09-14T17:25:22.470818 #1020] DEBUG -- [req_id cpi-101361]: Trying to find disk in : [wl01_ucs1_t2_wld_AC-ZHH-Prd-06_3009] PSC_SCS/disks
D, [2018-09-14T17:25:22.489774 #1020] DEBUG -- [req_id cpi-101361]: Running method 'SearchDatastore_Task'...
D, [2018-09-14T17:25:22.510412 #1020] DEBUG -- [req_id cpi-101361]: Starting task 'host.DatastoreBrowser.search'...
D, [2018-09-14T17:25:23.534618 #1020] DEBUG -- [req_id cpi-101361]: Finished task 'host.DatastoreBrowser.search' after 1.024069368 seconds
I, [2018-09-14T17:25:23.534715 #1020]  INFO -- [req_id cpi-101361]: Persistent disk was moved: moving disk to expected location
D, [2018-09-14T17:25:23.534789 #1020] DEBUG -- [req_id cpi-101361]: Running method 'ReconfigVM_Task'...
D, [2018-09-14T17:25:23.561605 #1020] DEBUG -- [req_id cpi-101361]: Starting task 'VirtualMachine.reconfigure'...
D, [2018-09-14T17:25:24.586734 #1020] DEBUG -- [req_id cpi-101361]: Finished task 'VirtualMachine.reconfigure' after 1.024941824 seconds
I, [2018-09-14T17:25:24.586857 #1020]  INFO -- [req_id cpi-101361]: Detached 1 persistent disk(s)
I, [2018-09-14T17:25:24.586938 #1020]  INFO -- [req_id cpi-101361]: Renaming 1 persistent disk(s)
D, [2018-09-14T17:25:24.784979 #1020] DEBUG -- [req_id cpi-101361]: Running method 'MakeDirectory'...
I, [2018-09-14T17:25:24.800471 #1020]  INFO -- [req_id cpi-101361]: Moving disk: [wl01_ucs1_t2_wld_AC-ZHH-Prd-06_3007] vm-12e04237-3d13-4c3d-91ce-90939b3198aa/vm-12e04237-3d13-4c3d-91ce-90939b3198aa_7550.vmdk to [wl01_ucs1_t2_wld_AC-ZHH-
Prd-06_3007] PSC_SCS/disks/disk-472ad9a9-2e29-4d30-a16c-2fbf75c341c1.vmdk
D, [2018-09-14T17:25:24.800619 #1020] DEBUG -- [req_id cpi-101361]: Running method 'MoveVirtualDisk_Task'...
D, [2018-09-14T17:25:24.822572 #1020] DEBUG -- [req_id cpi-101361]: Starting task 'VirtualDiskManager.moveVirtualDisk'...
W, [2018-09-14T17:25:25.847848 #1020]  WARN -- [req_id cpi-101361]: Error running task 'VirtualDiskManager.moveVirtualDisk'. Failed with message 'Insufficient disk space on datastore ''.'.
I, [2018-09-14T17:25:25.848390 #1020]  INFO -- [req_id cpi-101361]: Finished detach_disk in 6.34 seconds
D, [2018-09-14T17:25:25.848834 #1020] DEBUG -- [req_id cpi-101361]: Running method 'Logout'...
, exit_status: pid 1020 exit 0
....
E, [2018-09-14T17:25:25.900298 #19055] [instance_update(galera/0d6dfc15-3383-458c-a064-b992d8345eb7 (1))] ERROR -- DirectorJobRunner: Error updating instance: #<Bosh::Clouds::ExternalCpi::UnknownError: Unknown CPI error 'Unknown' with me
ssage 'Insufficient disk space on datastore ''.' in 'detach_disk' CPI method (CPI request ID: 'cpi-101361')>
/var/vcap/data/packages/director/a6212aba1f2c3d3717bf3a139340a97f253876a0/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/cloud/external_cpi.rb:194:in `handle_error'
/var/vcap/data/packages/director/a6212aba1f2c3d3717bf3a139340a97f253876a0/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/cloud/external_cpi.rb:106:in `invoke_cpi_method'
/var/vcap/data/packages/director/a6212aba1f2c3d3717bf3a139340a97f253876a0/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/cloud/external_cpi.rb:65:in `detach_disk'
....
D, [2018-09-14T17:25:25.935364 #19055] [task:41145] DEBUG -- DirectorJobRunner: (0.000284s) (conn: 69920697371340) UPDATE `tasks` SET `event_output` = CONCAT(`event_output`, '{\"time\":1536945925,\"error\":{\"code\":100,\"message\":\"Unknown CPI error \'Unknown\' with message \'Insufficient disk space on datastore \'\'.\' in \'detach_disk\' CPI method (CPI request ID: \'cpi-101361\')\"}}\n') WHERE (`id` = 41145)
D, [2018-09-14T17:25:25.936001 #19055] [task:41145] DEBUG -- DirectorJobRunner: (0.000528s) (conn: 69920697371340) COMMIT
E, [2018-09-14T17:25:25.936137 #19055] [task:41145] ERROR -- DirectorJobRunner: Unknown CPI error 'Unknown' with message 'Insufficient disk space on datastore ''.' in 'detach_disk' CPI method (CPI request ID: 'cpi-101361')
```

**vCenter Error Log**
```
2018-09-14T17:25:25.400478+00:00 psrvwl01vce0401 vpxd 14466 - -  Event [1973832] [1-1] 
[2018-09-14T17:25:24.854368Z] [vim.event.DatastoreFileMovedEvent] [info] [SCCLOUDINFRA\SA-Prd-PSC_SCS_AC6] [WL01] [1973831] 
[Move of file or directory [wl01_ucs1_t2_wld_AC-ZHH-Prd-06_3007] vm-12e04237-3d13-4c3d-91ce-90939b3198aa/vm-12e04237-3d13-4c3d-91ce-90939b3198aa_7550.vmdk from wl01_ucs1_t2_wld_AC-ZHH-Prd-06_3007 to wl01_ucs1_t2_wld_AC-ZHH-Prd-06_3007 as [wl01_ucs1_t2_wld_AC-ZHH-Prd-06_3007] PSC_SCS/disks/disk-472ad9a9-2e29-4d30-a16c-2fbf75c341c1.vmdk 
was initiated from 'HTTPClient/1.0 (2.8.3, ruby 2.4.4 (2018-03-28))@100.107.92.202' and completed with status 'Failure']
```

**Expected behavior**
The CPI should check before issuing the disk move/rename if the datastore still has enough capacity left. Otherwise it should choose another datastore to move/copy the disk to.

**Release Version & Related Info (please complete the following information):**
 - CPI Version `v50`
 - vCenter Version `v6.5`

**Comment by nehagjain15** [comment]
Thanks you @JamesClonk. I have created a [tracker story](https://www.pivotaltracker.com/story/show/160565671) for this issue. Will update you when we get to it.
