### ISSUE TITLE
`Address family not supported by protocol` on IPv6-enabled VCSAs

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh-vsphere-cpi-release#153]
**Describe the bug**

When uploading a stemcell to an IPv6-enabled VCSA, you may get an `Address family not supported by protocol` error

**To Reproduce**

1. Have a dual-stack VCSA
1. Have an IPv4-only BOSH
1.  Upload a stemcell

**CPI Error Log**

```
Rescued Unknown: Address family not supported by protocol - Address family not supported by protocol - socket(2) for "vcenter-67.nono.io" port 443 (vcenter-67.nono.io:443). backtrace: /var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:21:in `create_socket'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/base_http_client.rb:76:in `do_request'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/base_http_client.rb:43:in `post'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/soap/stub_adapter.rb:25:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:46:in `block in invoke_method'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/retryer.rb:9:in `block in try'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/retryer.rb:8:in `times'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/retryer.rb:8:in `try'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:33:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmodl/managed_object.rb:13:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmodl/managed_object.rb:45:in `block (3 levels) in finalize'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/soap/stub_adapter.rb:55:in `invoke_property'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:85:in `invoke_property'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmodl/managed_object.rb:17:in `invoke_property'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmodl/managed_object.rb:30:in `block (3 levels) in finalize'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/vcenter_client.rb:23:in `initialize'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/cloud.rb:55:in `new'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/cloud.rb:55:in `initialize'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere.rb:79:in `new'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere.rb:79:in `initialize'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:37:in `new'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:37:in `block in <top (required)>'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:80:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:42:in `<top (required)>'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-09-24T15:29:25.863393 #12636]  INFO -- [req_id cpi-297143]: Starting info...
D, [2018-09-24T15:29:25.867674 #12636] DEBUG -- [req_id cpi-297143]: Running method 'RetrieveServiceContent'...
I, [2018-09-24T15:29:25.929591 #12636]  INFO -- [req_id cpi-297143]: Finished info in 0.07 seconds
Rescued Unknown: Address family not supported by protocol - Address family not supported by protocol - socket(2) for "vcenter-67.nono.io" port 443 (vcenter-67.nono.io:443). backtrace: /var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:21:in `create_socket'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/base_http_client.rb:76:in `do_request'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/base_http_client.rb:43:in `post'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/soap/stub_adapter.rb:25:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:46:in `block in invoke_method'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/retryer.rb:9:in `block in try'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/retryer.rb:8:in `times'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/retryer.rb:8:in `try'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:33:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmodl/managed_object.rb:13:in `invoke_method'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmodl/managed_object.rb:45:in `block (3 levels) in finalize'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/soap/stub_adapter.rb:55:in `invoke_property'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb:85:in `invoke_property'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmodl/managed_object.rb:17:in `invoke_property'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmodl/managed_object.rb:30:in `block (3 levels) in finalize'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/vcenter_client.rb:23:in `initialize'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/cloud.rb:55:in `new'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere/cloud.rb:55:in `initialize'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere.rb:79:in `new'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/cloud/vsphere.rb:79:in `initialize'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:37:in `new'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:37:in `block in <top (required)>'
/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:80:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:42:in `<top (required)>'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'
/var/vcap/data/packages/ruby-2.4-r4/c8389dd95036a71df5213fafe665e7c72103dc00/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'/var/vcap/data/packages/vsphere_cpi/7a1eae0465f2b7c54d1be43377919165a49dd9f7/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-09-24T15:29:39.295966 #12645]  INFO -- [req_id cpi-920945]: Starting info...
D, [2018-09-24T15:29:39.308005 #12645] DEBUG -- [req_id cpi-920945]: Running method 'RetrieveServiceContent'...
I, [2018-09-24T15:29:39.545847 #12645]  INFO -- [req_id cpi-920945]: Finished info in 0.25 seconds
```

**Expected behavior**

I'd expect the stemcell to be uploaded

**Screenshots**

**Release Version & Related Info (please complete the following information):**
 - CPI Version 50
 - BOSH Director Version 267.5.0
 - Stemcell Name & Version 97.15
 - vCenter Version 6.7
 - NSX(T/V) Version (If using) N/A

**Additional context**

**Comment by EleanorRigby** [comment]
Is `IPv6` support enabled on the esxi hosts?

**Comment by cunnie** [comment]
This is a very simple way to cause the failure (run this command on the BOSH Director):
```bash
echo '{"method":"info","arguments":[],"context":{"director_uuid":"blah"}}' |
  PATH=/var/vcap/packages/ruby-2.4-r4/bin:/var/vcap/packages/iso9660wrap/bin:$PATH \
  BUNDLE_GEMFILE=/var/vcap/packages/vsphere_cpi/Gemfile \
  /var/vcap/packages/ruby-2.4-r4/bin/bundle exec \
  /var/vcap/packages/vsphere_cpi/bin/vsphere_cpi \
  /var/vcap/jobs/vsphere_cpi/config/cpi.json

```

**Comment by nehagjain15** [comment]
@cunnie 
The error that you are seeing is raised when vcenter_client is being initialized and during the deployment of director each of the method that you have listed does that successfully. 
It is just that when the call is made from deployed director vm an error is being raised. So, I am not sure if thats where the problem is.
We will try to do the same setup and will update you on how it goes.

**Comment by cunnie** [comment]
**The error does not exhibit on the Ops Manager** when invoked with the same `cpi.json` file as the BOSH Director's:
```bash
echo '{"method":"info","arguments":[],"context":{"director_uuid":"blah"}}' |
  BUNDLE_GEMFILE=$(echo /home/tempest-web/.bosh/installations/*/packages/vsphere_cpi/Gemfile) \
  /home/tempest-web/.bosh/installations/*/packages/ruby-2.4-r4/bin/bundle exec \
  /home/tempest-web/.bosh/installations/*/packages/vsphere_cpi/bin/vsphere_cpi \
  cpi.json
/home/tempest-web/.bosh/installations/bd6289cb-4fda-4f2d-4f3d-52c4d1a1179a/packages/vsphere_cpi/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-09-28T14:51:56.471096 #31714]  INFO -- [req_id ]: Starting info...
D, [2018-09-28T14:51:56.473548 #31714] DEBUG -- : Running method 'RetrieveServiceContent'...
D, [2018-09-28T14:51:56.575536 #31714] DEBUG -- : Running method 'Login'...
I, [2018-09-28T14:51:56.753872 #31714]  INFO -- [req_id ]: Finished info in 0.28 seconds
{"result":{"stemcell_formats":["vsphere-ovf","vsphere-ova"]},"error":null,"log":""}D, [2018-09-28T14:51:56.755447 #31714] DEBUG -- : Running method 'Logout'...
```

**Comment by cunnie** [comment]
Workaround: use **vCenter IPv4 address** not hostname in BOSH manifest

Short version: if 

- the BOSH Director (or the Operations Manager) is not on the same IPv4 subnet as...
-  a dual-stack (both IPv4 and IPv6) vcenter (e.g. vcenter-67.nono.io), 
- and the hostname (vcenter-67.nono.io) resolves both IPv4 and IPv6 addresses,
- and the hostname of the vcenter (_not_ the IP address) is used in the BOSH manifest
- then the command will fail and generate the stacktrace above.

**Comment by EleanorRigby** [comment]
@cunnie : Thanks for clear triage of the issue. Do you think CPI can change any source code to reflect this? or this is mostly for documentation and clarity?

**Comment by cunnie** [comment]
I'm closing this issue because there's a workaround.

**Comment by cunnie** [comment]
Addendum: a similar error may show up with an IPv4 Director and a dual-stack ESXi host:
```
Task 751 | 11:44:36 | Creating missing vms: worker/d878cec9-14a9-4aaf-a55f-e5b890379518 (0) (00:00:16)
                    L Error: Unknown CPI error 'Unknown' with message 'Address family not supported by protocol - Address family not supported by protocol - socket(2) for "esxi-2.nono.io" port 443 (esxi-2.nono.io:443)' in 'create_vm' CPI method (CPI request ID: 'cpi-604442')
```
When this happens, make sure that the BOSH Director can reach the ESXi host over the IPv4 network (i.e. that there's no firewall rule blocking it). In my case, I had a firewall rule blocking the Director's subnet (10.2.0.0/24) from reaching the vSphere subnet (10.0.9.0/24) with exceptions for the Director to reach the vCenter and two ESXi hosts. Adding an exception for the Director to reach the newly-added third ESXi host (esxi-2.nono.io) fixed the problem for me.

| Hostname | IP Addr |
|---|---|
| bosh-vsphere.nono.io | 10.2.0.250<br />73.189.219.4 |
| esxi-2.nono.io | 10.0.9.42<br />2601:646:0100:69f0::42 |
