### ISSUE TITLE
Unknown CPI error 'Unknown' with message 'Unable to communicate with the remote host, since it is disconnected.' in 'create_vm' CPI method

### ISSUE THREAD

**Issue by agregory999** [cloudfoundry/bosh-vsphere-cpi-release#185]
**Describe the bug**
When an ESXi host is in a non-expected state, but not maintenance mode or disconnected, BOSH seems to try to place VMs there.  In this instance it was a smoke test VM, but we were unable to create the VM on multiple consecutive attempts even though there were other operational hosts in the AZ that was specified. BOSH was unable to select a different host.

**To Reproduce**
1. Have an AZ with multiple ESXi hosts
2. Force a host to show up as "Not Responding" - some clues on how this might happen are here:
https://kb.vmware.com/s/article/1003409?lang=en_US
3. Use a deployment that specifies the AZ that the host is in, and attempt to create VMs until that host causes the failure.

**CPI Error Log**

$ bosh task 129509 --cpi
Using environment 'bosh.xxxxxx.xxxxx.com' as user 'director' (bosh.*.read, openid, bosh.*.admin, bosh.read, bosh.admin)
 
Task 129509
 
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-31T17:03:51.730751 #7304]  INFO -- [req_id cpi-905857]: Starting info...
D, [2018-12-31T17:03:51.732807 #7304] DEBUG -- [req_id cpi-905857]: Running method 'RetrieveServiceContent'...
D, [2018-12-31T17:03:51.775731 #7304] DEBUG -- [req_id cpi-905857]: Running method 'Login'...
I, [2018-12-31T17:03:51.857942 #7304]  INFO -- [req_id cpi-905857]: Finished info in 0.13 seconds
D, [2018-12-31T17:03:51.858552 #7304] DEBUG -- [req_id cpi-905857]: Running method 'Logout'...
Rescued Unknown: Unable to communicate with the remote host, since it is disconnected.. backtrace: /var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/retryer.rb:13:in `try'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/task_runner.rb:14:in `run'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/vcenter_client.rb:50:in `wait_for_task'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/vm_creator.rb:98:in `create'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/cloud.rb:292:in `block in create_vm'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/cloud.rb:243:in `create_vm'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:42:in `<top (required)>'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-31T17:03:56.874302 #7323]  INFO -- [req_id cpi-219537]: Starting create_vm...
D, [2018-12-31T17:03:56.876431 #7323] DEBUG -- [req_id cpi-219537]: Running method 'RetrieveServiceContent'...
D, [2018-12-31T17:03:56.920033 #7323] DEBUG -- [req_id cpi-219537]: Running method 'Login'...
D, [2018-12-31T17:03:56.994519 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
D, [2018-12-31T17:03:56.999790 #7323] DEBUG -- [req_id cpi-219537]: Running method 'CreateContainerView'...
D, [2018-12-31T17:03:57.112692 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:03:57.178347 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:03:57.244433 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:03:57.310986 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:03:57.375037 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:03:57.458804 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:03:57.532196 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:03:57.624078 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:03:57.708730 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:03:57.731283 #7323] DEBUG -- [req_id cpi-219537]: All clusters provided: {"omaVXR-AZ1"=>#<VSphereCloud::ClusterConfig:0x000055d8edb037b0 @name="omaVXR-AZ1", @config={"resource_pool"=>"NonProd_AZ1_RP"}>, "omaVXR-AZ2"=>#<VSphereCloud::ClusterConfig:0x000055d8edb03760 @name="omaVXR-AZ2", @config={"resource_pool"=>"NonProd_AZ2_RP"}>, "omaVXR-AZ3"=>#<VSphereCloud::ClusterConfig:0x000055d8edb03710 @name="omaVXR-AZ3", @config={"resource_pool"=>"NonProd_AZ3_RP"}>}
D, [2018-12-31T17:03:57.731436 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
I, [2018-12-31T17:03:57.802165 #7323]  INFO -- [req_id cpi-219537]: Using global ephemeral disk datastore pattern: ^(NonProd_AZ1_DS|NonProd_AZ2_DS|NonProd_AZ3_DS)$
D, [2018-12-31T17:03:57.841911 #7323] DEBUG -- [req_id cpi-219537]: Found requested resource pool: <[Vim.ResourcePool] resgroup-437>
D, [2018-12-31T17:04:02.086228 #7323] DEBUG -- [req_id cpi-219537]: Initial Storage Options for creating ephemeral disk from pattern: ["NonProd_AZ3_DS"]
D, [2018-12-31T17:04:02.086348 #7323] DEBUG -- [req_id cpi-219537]: Storage Options for creating ephemeral disk are: ["NonProd_AZ3_DS"]
I, [2018-12-31T17:04:02.086437 #7323]  INFO -- [req_id cpi-219537]: Checking if ip '10.235.68.34' is in use
D, [2018-12-31T17:04:02.086509 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByIp'...
I, [2018-12-31T17:04:02.102199 #7323]  INFO -- [req_id cpi-219537]: No IP conflicts detected
I, [2018-12-31T17:04:02.102424 #7323]  INFO -- [req_id cpi-219537]: Creating vm: vm-cc96b4ba-204c-489b-be41-8ce339fdedca on <[Vim.ClusterComputeResource] domain-c11> stored in <[Vim.Datastore] datastore-459>
D, [2018-12-31T17:04:02.102502 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
D, [2018-12-31T17:04:02.106621 #7323] DEBUG -- [req_id cpi-219537]: Running method 'CreateContainerView'...
D, [2018-12-31T17:04:02.208568 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:02.274248 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:02.342599 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:02.408939 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:02.475364 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:02.540929 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:02.611286 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:02.689535 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:02.773584 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
I, [2018-12-31T17:04:02.794135 #7323]  INFO -- [req_id cpi-219537]: Searching for stemcell sc-731be3a3-5aa1-4447-9ec9-eae6ce34416d on datastore NonProd_AZ3_DS
D, [2018-12-31T17:04:02.794231 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
D, [2018-12-31T17:04:02.798212 #7323] DEBUG -- [req_id cpi-219537]: Running method 'CreateContainerView'...
D, [2018-12-31T17:04:02.896524 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:02.966607 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:03.034935 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:03.105207 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:03.172722 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:03.250750 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:03.321594 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:03.389006 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:03.460132 #7323] DEBUG -- [req_id cpi-219537]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-31T17:04:03.542292 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
I, [2018-12-31T17:04:04.756259 #7323]  INFO -- [req_id cpi-219537]: Cloning vm: (VSphereCloud::Resources::VM (cid="sc-731be3a3-5aa1-4447-9ec9-eae6ce34416d")) to vm-cc96b4ba-204c-489b-be41-8ce339fdedca
D, [2018-12-31T17:04:04.756435 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
D, [2018-12-31T17:04:04.782670 #7323] DEBUG -- [req_id cpi-219537]: Found requested resource pool: <[Vim.ResourcePool] resgroup-437>
D, [2018-12-31T17:04:04.783406 #7323] DEBUG -- [req_id cpi-219537]: Running method 'CloneVM_Task'...
D, [2018-12-31T17:04:04.819319 #7323] DEBUG -- [req_id cpi-219537]: Starting task 'VirtualMachine.clone'...
W, [2018-12-31T17:04:04.828601 #7323]  WARN -- [req_id cpi-219537]: Error running task 'VirtualMachine.clone'. Failed with message 'Unable to communicate with the remote host, since it is disconnected.'.
D, [2018-12-31T17:04:05.829327 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
D, [2018-12-31T17:04:05.836884 #7323] DEBUG -- [req_id cpi-219537]: Running method 'CloneVM_Task'...
W, [2018-12-31T17:04:05.857838 #7323]  WARN -- [req_id cpi-219537]: Retrying task 'VirtualMachine.clone', 1 attempts so far...
W, [2018-12-31T17:04:05.866267 #7323]  WARN -- [req_id cpi-219537]: Error running task 'VirtualMachine.clone'. Failed with message 'Unable to communicate with the remote host, since it is disconnected.'.
D, [2018-12-31T17:04:07.866616 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
D, [2018-12-31T17:04:07.871943 #7323] DEBUG -- [req_id cpi-219537]: Running method 'CloneVM_Task'...
W, [2018-12-31T17:04:07.891828 #7323]  WARN -- [req_id cpi-219537]: Retrying task 'VirtualMachine.clone', 2 attempts so far...
W, [2018-12-31T17:04:07.900584 #7323]  WARN -- [req_id cpi-219537]: Error running task 'VirtualMachine.clone'. Failed with message 'Unable to communicate with the remote host, since it is disconnected.'.
D, [2018-12-31T17:04:11.900970 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
D, [2018-12-31T17:04:11.906403 #7323] DEBUG -- [req_id cpi-219537]: Running method 'CloneVM_Task'...
W, [2018-12-31T17:04:11.924803 #7323]  WARN -- [req_id cpi-219537]: Retrying task 'VirtualMachine.clone', 3 attempts so far...
W, [2018-12-31T17:04:11.933008 #7323]  WARN -- [req_id cpi-219537]: Error running task 'VirtualMachine.clone'. Failed with message 'Unable to communicate with the remote host, since it is disconnected.'.
D, [2018-12-31T17:04:19.933418 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
D, [2018-12-31T17:04:19.940108 #7323] DEBUG -- [req_id cpi-219537]: Running method 'CloneVM_Task'...
W, [2018-12-31T17:04:19.959818 #7323]  WARN -- [req_id cpi-219537]: Retrying task 'VirtualMachine.clone', 4 attempts so far...
W, [2018-12-31T17:04:19.967863 #7323]  WARN -- [req_id cpi-219537]: Error running task 'VirtualMachine.clone'. Failed with message 'Unable to communicate with the remote host, since it is disconnected.'.
D, [2018-12-31T17:04:35.968236 #7323] DEBUG -- [req_id cpi-219537]: Running method 'FindByInventoryPath'...
D, [2018-12-31T17:04:35.980902 #7323] DEBUG -- [req_id cpi-219537]: Running method 'CloneVM_Task'...
W, [2018-12-31T17:04:36.002967 #7323]  WARN -- [req_id cpi-219537]: Retrying task 'VirtualMachine.clone', 5 attempts so far...
W, [2018-12-31T17:04:36.013130 #7323]  WARN -- [req_id cpi-219537]: Error running task 'VirtualMachine.clone'. Failed with message 'Unable to communicate with the remote host, since it is disconnected.'.
E, [2018-12-31T17:04:36.013369 #7323] ERROR -- [req_id cpi-219537]: Error in creating vm: Unable to communicate with the remote host, since it is disconnected., Backtrace - /var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/retryer.rb:13:in `try'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/task_runner.rb:14:in `run'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/vcenter_client.rb:50:in `wait_for_task'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/vm_creator.rb:98:in `create'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/cloud.rb:292:in `block in create_vm'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/lib/cloud/vsphere/cloud.rb:243:in `create_vm'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/data/packages/vsphere_cpi/309a27944e73f2c816ce55254f976804911cf9eb/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:42:in `<top (required)>'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'
/var/vcap/data/packages/ruby-2.4-r4/5df971e1c8cad0e2661499cc97e09faf3c81794d/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'
I, [2018-12-31T17:04:36.013664 #7323]  INFO -- [req_id cpi-219537]: Finished create_vm in 39.14 seconds
D, [2018-12-31T17:04:36.014071 #7323] DEBUG -- [req_id cpi-219537]: Running method 'Logout'...
 
Task 129509 error
 
Capturing task '129509' output:
  Expected task '129509' to succeed but state is 'error'
 
Exit code 1

**Expected behavior**
Any status other than fully operational should cause BOSH to seamlessly select a working host to place VMs on.

**Screenshots**

![vsphere-not-responding](https://user-images.githubusercontent.com/30056870/50641809-2a5f0900-0f37-11e9-9cfa-e2eb643d5f61.jpg)

**Release Version & Related Info (please complete the following information):**
 - CPI Version 
vsphere 266.11.0
 - BOSH Director Version
PCF 2.2
 - Stemcell Name & Version
 - vCenter Version
6.5
 - NSX(T/V) Version (If using)
NSX-V (not sure exact version)

**Additional context**

**Comment by EleanorRigby** [comment]
Can you provide correct CPI version? The above is only Director version.
If you are using opsMan , you can find CPI version in opsman release notes.

**Comment by EleanorRigby** [comment]
Also the CPI log above is impossible to read in current form. The copy and paste might have deleted new line characters. Is it possible for you to paste it again maintaining the line breaks.

**Comment by EleanorRigby** [comment]
On a cursory glance , it seems DRS is selecting a wrong host to put VM on. vSphere CPI only selects a datastore and a cluster. Cluster from the BOSH Director's chosen AZ and datastore from `persistent_datastore_pattern` and `ephemeral_pattern` (global config) or from `vm_type` in cloud config.

Could you provide more information on 
  - How AZ's look and what clusters they are made up from?
  - Is the non functional host only host in the cluster?
  - What's the datastore pattern (ephemeral & persistent) and how many hosts are connected to each datastore? 

If possible , can you try this experiment : 
What happens if you manually try to create a VM on the cluster by right clicking in vCenter UI on the cluster and then create VM. Does the placement automatically happen on the non-functional host? if yes, probably DRS is not taking care of rejecting non-functional host.

**Comment by EleanorRigby** [comment]
@agregory999 , see above ^^

**Comment by agregory999** [comment]
Couple updates and comments:
1) Earlier today they put the host into maintenance mode (actually to have HW team look at it), and immediately things work again, smoke test/new VM, etc.
2) The cluster has 5 hosts, the other 4 were fine. 3 AZs with the same, and PCF spread across all.
3) If BOSH and OpsMan aren't specifying host, I agree with you that DRS seems like it.  Perhaps it doesn't recognize the non-responsiveness and just sees an empty host (no VMs), then selects it for all new VMs and fails.  Guessing there.

We'll work with VMW support on this and update the thread.
