### ISSUE TITLE
Unknown CPI error ''Unknown'' with message ''The object[s] ''<[Vim.VirtualMachine] vm-11141>'' should have the following properties: [\"parent\"]\n, but they were missing these...

### ISSUE THREAD

**Issue by shiveshabhishek** [cloudfoundry/bosh-vsphere-cpi-release#294]
**Describe the bug**
While bosh is trying to recreate the VMs during scan & fix, getting the following error message:
```
{"time":1621284316,"error":{"code":100,"message":"Error resolving problem ''5180'': Unknown CPI error ''Unknown'' with message ''The object[s] ''<[Vim.VirtualMachine] vm-11141>'' should have the following properties: [\"parent\"]\n, but they were missing these: #<Set: {\"parent\"}>\n.'' in ''delete_vm'' CPI method (CPI request ID: ''cpi-926763'')"}}
```

**CPI Error Log**
```
root@in2tive-virtual-machine:~/pks-1.10.1# bosh task 11537 --cpi
Using environment '192.168.161.4' as client 'ops_manager'

Task 11537

I, [2021-05-17T20:36:44.100404 #6580]  INFO -- [req_id cpi-307220]: Starting info...
I, [2021-05-17T20:36:44.100563 #6580]  INFO -- : Fetching vSphere version to locate SDK
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2021-05-17T20:36:51.916219 #6580]  INFO -- : Loaded vSphere 7.0 SDK
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/nsxt/nsxt_client/api/upgrade_node_upgrade_api.rb:145: warning: character class has '-' without escape: /^[a-zA-Z0-9-.]+$/
D, [2021-05-17T20:37:35.842172 #6580] DEBUG -- [req_id cpi-307220]: Running method 'RetrieveServiceContent'...
D, [2021-05-17T20:37:36.591177 #6580] DEBUG -- [req_id cpi-307220]: Running method 'Login'...
I, [2021-05-17T20:37:37.188429 #6580]  INFO -- [req_id cpi-307220]: Finished info in 53.09 seconds
D, [2021-05-17T20:37:37.189040 #6580] DEBUG -- [req_id cpi-307220]: Running method 'Logout'...
I, [2021-05-17T20:37:43.970079 #6629]  INFO -- [req_id cpi-373835]: Starting has_vm...
I, [2021-05-17T20:37:43.970209 #6629]  INFO -- : Fetching vSphere version to locate SDK
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2021-05-17T20:37:53.845703 #6629]  INFO -- : Loaded vSphere 7.0 SDK
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/nsxt/nsxt_client/api/upgrade_node_upgrade_api.rb:145: warning: character class has '-' without escape: /^[a-zA-Z0-9-.]+$/
D, [2021-05-17T20:38:32.874394 #6629] DEBUG -- [req_id cpi-373835]: Running method 'RetrieveServiceContent'...
D, [2021-05-17T20:38:33.342047 #6629] DEBUG -- [req_id cpi-373835]: Running method 'Login'...
D, [2021-05-17T20:38:34.012382 #6629] DEBUG -- [req_id cpi-373835]: Running method 'FindByInventoryPath'...
D, [2021-05-17T20:38:34.022636 #6629] DEBUG -- [req_id cpi-373835]: Running method 'CreateContainerView'...
D, [2021-05-17T20:38:34.435179 #6629] DEBUG -- [req_id cpi-373835]: Running method 'ContinueRetrievePropertiesEx'...
I, [2021-05-17T20:38:34.885858 #6629]  INFO -- [req_id cpi-373835]: Finished has_vm in 50.92 seconds
D, [2021-05-17T20:38:34.886620 #6629] DEBUG -- [req_id cpi-373835]: Running method 'Logout'...
I, [2021-05-17T20:38:56.939772 #6685]  INFO -- [req_id cpi-117651]: Starting info...
I, [2021-05-17T20:38:56.939992 #6685]  INFO -- : Fetching vSphere version to locate SDK
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2021-05-17T20:39:03.217852 #6685]  INFO -- : Loaded vSphere 7.0 SDK
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/nsxt/nsxt_client/api/upgrade_node_upgrade_api.rb:145: warning: character class has '-' without escape: /^[a-zA-Z0-9-.]+$/
D, [2021-05-17T20:39:42.163991 #6685] DEBUG -- [req_id cpi-117651]: Running method 'RetrieveServiceContent'...
D, [2021-05-17T20:39:42.943679 #6685] DEBUG -- [req_id cpi-117651]: Running method 'Login'...
I, [2021-05-17T20:39:43.918671 #6685]  INFO -- [req_id cpi-117651]: Finished info in 46.98 seconds
D, [2021-05-17T20:39:43.919718 #6685] DEBUG -- [req_id cpi-117651]: Running method 'Logout'...
Rescued Unknown: The object[s] '<[Vim.VirtualMachine] vm-11141>' should have the following properties: ["parent"]
, but they were missing these: #<Set: {"parent"}>
.. backtrace: /var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/cloud/vsphere/cloud_searcher.rb:52:in `block (2 levels) in get_properties'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/cloud/vsphere/cloud_searcher.rb:38:in `each'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/cloud/vsphere/cloud_searcher.rb:38:in `block in get_properties'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/common.rb:119:in `retryable'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/cloud/vsphere/cloud_searcher.rb:34:in `get_properties'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/cloud/vsphere/cloud_searcher.rb:16:in `get_property'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/cloud/vsphere/vcenter_client.rb:58:in `find_parent'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/cloud/vsphere/agent_env.rb:63:in `clean_env'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/cloud/vsphere/cloud.rb:476:in `block in delete_vm'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/cloud/vsphere/cloud.rb:453:in `delete_vm'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/2.6.0/forwardable.rb:230:in `delete_vm'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `public_send'
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:48:in `<top (required)>'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:46:in `block in <top (required)>'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/05e1186a4b28b32055b3ea4edd89dc0c54362dd5/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:34:in `<top (required)>'
/var/vcap/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `load'
/var/vcap/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `<main>'I, [2021-05-17T20:39:51.406550 #6742]  INFO -- [req_id cpi-926763]: Starting delete_vm...
I, [2021-05-17T20:39:51.406677 #6742]  INFO -- : Fetching vSphere version to locate SDK
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2021-05-17T20:39:57.998750 #6742]  INFO -- : Loaded vSphere 7.0 SDK
/var/vcap/data/packages/vsphere_cpi/f06564296f1d8befb42717d49781d99c7138e69a/lib/nsxt/nsxt_client/api/upgrade_node_upgrade_api.rb:145: warning: character class has '-' without escape: /^[a-zA-Z0-9-.]+$/
D, [2021-05-17T20:40:36.872485 #6742] DEBUG -- [req_id cpi-926763]: Running method 'RetrieveServiceContent'...
D, [2021-05-17T20:40:37.648526 #6742] DEBUG -- [req_id cpi-926763]: Running method 'Login'...
I, [2021-05-17T20:40:38.252464 #6742]  INFO -- [req_id cpi-926763]: Deleting vm: vm-79187519-ba3d-4828-8410-11ee8bef1e47
D, [2021-05-17T20:40:38.252999 #6742] DEBUG -- [req_id cpi-926763]: Running method 'FindByInventoryPath'...
D, [2021-05-17T20:40:38.589299 #6742] DEBUG -- [req_id cpi-926763]: Running method 'CreateContainerView'...
D, [2021-05-17T20:40:39.409757 #6742] DEBUG -- [req_id cpi-926763]: Running method 'ContinueRetrievePropertiesEx'...
I, [2021-05-17T20:40:44.047127 #6742]  INFO -- [req_id cpi-926763]: VM 'vm-79187519-ba3d-4828-8410-11ee8bef1e47' is already powered off, skipping power off task.
I, [2021-05-17T20:40:44.591236 #6742]  INFO -- [req_id cpi-926763]: Cleaning current agent env from vm 'vm-79187519-ba3d-4828-8410-11ee8bef1e47'
I, [2021-05-17T20:45:15.218437 #6742]  INFO -- [req_id cpi-926763]: Finished delete_vm in 323.81 seconds
D, [2021-05-17T20:45:15.219183 #6742] DEBUG -- [req_id cpi-926763]: Running method 'Logout'...

Task 11537 error

Capturing task '11537' output:
  Expected task '11537' to succeed but state is 'error'

Exit code 1

```
**Expected behavior**
Ideally, bosh should re-create the VM during scan and fix
**Screenshots**
![image](https://user-images.githubusercontent.com/29581152/118555824-c1cbfc00-b780-11eb-8af8-027330cc6b13.png)

**Release Version & Related Info (please complete the following information):**
 - CPI Version 
 - BOSH Director Version: v2.10.8-build.168
 - Stemcell Name & Version: Tanzu Kubernetes Grid Integrated Edition Version 1.10.1-build.8 
 - vCenter Version :   7.0.2.00100
 - NSX(T/V) Version (If using)

**Comment by shiveshabhishek** [comment]
Some point to add:

We are using HA for API and DB for TKGI (2 API and 3 DB)

**Comment by cunnie** [comment]
Hi @shiveshabhishek ! Thanks for reporting this; we believe it's fixed in BOSH vSphere CPI release v59. If it's not fixed, let us know by re-opening this issue. Closing.

**Comment by shanmukhavsv** [comment]
with latest ops manager also i am facing same issue:


"error":"Unknown CPI error ''Unknown'' with message ''The object[s] ''<[Vim.VirtualMachine] vm-13093>'' should have the following properties: [\"parent\"]\n, but they were missing these: #<Set: {\"parent\"}>\n.'' in ''attach_disk'' CPI method (CPI request ID: ''cpi-155877'')"}}
{"time":1624838348,"error":{"code":100,"message":"Unknown CPI error ''Unknown'' with message ''The object[s] ''<[Vim.VirtualMachine] vm-13093>'' should have the following properties: [\"parent\"]\n, but they were missing these: #<Set: {\"parent\"}>\n.'' in ''attach_disk'' CPI method (CPI request ID: ''cpi-155877'')"}}
', "result_output" = '', "context_id" = 'eb81158a-a5ae-47af-ac9d-8da0759f4b6c' WHERE ("id" = 64)
D, [2021-06-27T23:59:08.893760 #3744] [task:64] DEBUG -- DirectorJobRunner: (0.000682s) (conn: 46945945533220) COMMIT
I, [2021-06-27T23:59:08.893921 #3744] []  INFO -- DirectorJobRunner: Task took 19 minutes 16.837824963000003 seconds to process.

Task 64 error

Capturing task '64' output:
  Expected task '64' to succeed but state is 'error'

Exit code 1
