### ISSUE TITLE
create_vm fails with postgres SQL error with CPI v72

### ISSUE THREAD

**Issue by JCL38-ORANGE** [cloudfoundry/bosh-vsphere-cpi-release#315]
**Describe the bug**
create_vm fails with postgres SQL error with CPI v72

**To Reproduce**
cloud_config extract : 
```
- name: tf-net-osb-data-plane-dedicated-priv
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: vxw-dvs-27-virtualwire-99-sid-7050-VXS_in_tf-net-osb-data-plane-dedicated-priv
    gateway: 192.168.61.1
    range: 192.168.61.0/24
    reserved:
    - 192.168.61.1 - 192.168.61.20
```

**CPI Error Log**
```
D, [2021-12-02T15:03:31.712189 #11308] [task:5894640] DEBUG -- DirectorJobRunner: (0.000524s) (conn: 47264853264400) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1638457411,"error":{"code":100,"message":"PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type boolean: \"cloud_properties\"\nLINE 1: ...68.61.34'') AND (''netmask'' = ''255.255.255.0'') AND (''cloud_pro...\n                                                             ^\n"}}
') WHERE ("id" = 5894640)
D, [2021-12-02T15:03:31.752886 #11308] [task:5894640] DEBUG -- DirectorJobRunner: (0.040494s) (conn: 47264853264400) COMMIT
E, [2021-12-02T15:03:31.753338 #11308] [task:5894640] ERROR -- DirectorJobRunner: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type boolean: "cloud_properties"
LINE 1: ...68.61.34') AND ('netmask' = '255.255.255.0') AND ('cloud_pro...
                                                             ^

/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `exec'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `block in execute_query'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/database/logging.rb:43:in `log_connection_yield'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `execute_query'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:140:in `block in execute'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:116:in `check_disconnect_errors'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:140:in `execute'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:496:in `_execute'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:314:in `block (2 levels) in execute'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:518:in `check_database_errors'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:314:in `block in execute'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:314:in `execute'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/dataset/actions.rb:1083:in `execute'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:610:in `fetch_rows'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/dataset/actions.rb:937:in `with_sql_each'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/dataset/actions.rb:945:in `with_sql_first'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/shared/postgres.rb:1553:in `insert_select'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1709:in `_insert_select_raw'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1682:in `_insert'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1753:in `block (2 levels) in _save'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1015:in `around_create'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1750:in `block in _save'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1015:in `around_save'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1745:in `_save'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1465:in `block (2 levels) in save'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1905:in `block in checked_transaction'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:245:in `_transaction'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:220:in `block in transaction'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:186:in `transaction'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1905:in `checked_transaction'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1465:in `block in save'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1893:in `checked_save_failure'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1465:in `save'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:254:in `create'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/api/event_manager.rb:42:in `create_event'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/steps/create_vm_step.rb:166:in `add_event'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/steps/create_vm_step.rb:162:in `ensure in create'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/steps/create_vm_step.rb:162:in `create'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/steps/create_vm_step.rb:27:in `perform'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:39:in `block in run_agenda'
                /var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:36:in `each'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:36:in `run_agenda'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:21:in `block (5 levels) in run'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:20:in `block (4 levels) in run'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:50:in `with_thread_name'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/step_executor.rb:18:in `block (3 levels) in run'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/data/packages/director/87427387c8b374a15842eb951bb2cef3b10afb12/gem_home/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2021-12-02T15:03:31.755025 #11308] [task:5894640] DEBUG -- DirectorJobRunner: (0.000375s) (conn: 47264853268480) SELECT * FROM "tasks" WHERE "id" = 5894640
D, [2021-12-02T15:03:31.757519 #11308] [task:5894640] DEBUG -- DirectorJobRunner: (0.000131s) (conn: 47264854487260) BEGIN
D, [2021-12-02T15:03:31.758981 #11308] [task:5894640] DEBUG -- DirectorJobRunner: (0.000611s) (conn: 47264854487260) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2021-12-02 15:03:31.756516+0000', "description" = 'create deployment', "result" = 'PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type boolean:
LINE 1: ...68.61.34'') AND...', "output" = '/var/vcap/store/director/tasks/5894640', "checkpoint_time" = '2021-12-02 15:03:14.991645+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'y_7186f856-b982-41f9-9e60-c28dae205d1b', "started_at" = '2021-12-02 15:02:44.991574+0000', "event_output" = '{"time":1638457369,"stage":"Preparing deployment","tags":[],"total":1,"task":"Preparing deployment","index":1,"state":"started","progress":0}
```

**Expected behavior**
success for create_vm

**Release Version & Related Info (please complete the following information):**
 - CPI : 72
 - BOSH Director : 271.8.0
 - Stemcell : Bionic 1.34
 - vCenter : 6.7
 
**Additional context**
Bump CPI from v66 to v72

**Comment by rkoster** [comment]
@JCL38-ORANGE Just to double-check, the snippet to reproduce this issue is:
```yaml
networks:
- name: tf-net-osb-data-plane-dedicated-priv
  subnets:
    azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: vxw-dvs-27-virtualwire-99-sid-7050-VXS_in_tf-net-osb-data-plane-dedicated-priv
    gateway: 192.168.61.1
    range: 192.168.61.0/24
    reserved:
    - 192.168.61.1 - 192.168.61.20
```
Just want to make sure that the snippet used was actually valid yaml (the snippet you posted is not, but this could just be a markdown issue).

**Comment by JCL38-ORANGE** [comment]
Hello,

Sorry for my very late answer.
Yes I confirm your snippet.
Thanks and regards,
Jean-Christophe.
